#!/bin/sh

set -e

# Remove desktop shortcut from development menu


#update-rc.d -f ${build.finalName} remove
#
#if [ -e /var/log/${build.finalName}.log ]; then
#  rm /var/log/${build.finalName}.log
#fi

exit 0